/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/orca/Animation_Formal_Bow_withSkin.glb --transform --simplify --simplify-precision 0.25 
Files: public/orca/Animation_Formal_Bow_withSkin.glb [4.69MB] > /Users/kiyo/ORCX/ORCX_WEBSITE_NEW/Animation_Formal_Bow_withSkin-transformed.glb [769.26KB] (84%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Animation_Formal_Bow_withSkin-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.Hips} />
        </group>
        <skinnedMesh name="char1" geometry={nodes.char1.geometry} material={materials.Material_1} skeleton={nodes.char1.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/Animation_Formal_Bow_withSkin-transformed.glb')
