[site]
site = "www.orcx.co.jp"
account_id = "your_account_id"
zone_id = "your_zone_id"

[build]
command = "npm run build"
publish = "docs"

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' wss:; worker-src 'self' blob:; child-src 'self' blob:;"

[[headers]]
for = "/orca/*.glb"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "*"
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "http://*"
to = "https://:1"
status = 301
force = true 